version: "2"

formatters:
  enable:
    - gofmt

linters:
  disable:
    - errcheck
  exclusions:
    rules:
      - path: testing.go
        linters:
          - unused
      - path: client_mock.go
        linters:
          - unused
