version: "2"

formatters:
  enable:
    - gofmt

linters:
  disable:
    - errcheck
  exclusions:
    rules:
      - linters: [staticcheck]
        text: "ST1005" # Incorrectly formatted error string.
      - path: testing.go
        linters:
          - unused
      - path: client_mock.go
        linters:
          - unused
