
name: 'Upload provider'
description: |-
  Upload new provider version to GCS bucket.

inputs:
  registry-domain:
    description: 'Domain name of terraform registry.'
    required: true
  gcs-bucket:
    description: 'GCS bucket name'
    required: true
  gpg-key-id:
    description: 'GPG Key id'
    required: true
  gpg-pub-key:
    description: 'GPG pub key'
    required: true
  is-development:
    description: 'Whether this is a development registry'
    required: false
    default: 'false'

runs:
  using: 'node16'
  main: 'dist/index.js'
        