name: 'Backport Fixes'

on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
    branches:
      - 'release/*'

jobs:
  backport:
    name: Backport
    runs-on: ubuntu-latest
    steps:
    - name: Sudo GitHub Token
      id: sudo_github_token
      uses: tibdex/github-app-token@v1.8.2
      with:
        app_id: ${{vars.SUDO_GHA_APP_ID}}
        installation_id: ${{vars.SUDO_GHA_APP_INSTALLATION_ID}}
        private_key: ${{secrets.SUDO_GHA_APP_PRIVATE_KEY}}

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        filter: blob:none
        show-progress: false

    - name: Backport
      uses: Scalr/actions/2-pr-backport@master
      with:
        token: ${{steps.sudo_github_token.outputs.token}}
        branches_ordering_rule: >-
          release/*.*.*
          master
        base_branch: ${{github.base_ref}}
        head_branch: ${{github.head_ref}}
