name: '🚀 Publish the documentation'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Readme documentation version'
        required: true
        type: string
        default: '0.0.5'
      dry:
        description: 'Perform a dry run (preview the changes without publishing)'
        required: true
        type: boolean
        default: true

jobs:
  docs:
    name: Publish Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish
        uses: readmeio/rdme@v8
        with:
          rdme: docs ./docs --key=${{ secrets.README_API_KEY }} --version=${{ inputs.version }} ${{ inputs.dry == true && '--dryRun' || '' }}
