name: Manage Approved Label

on:
  pull_request_review:
    types: [submitted]

jobs:
  approval-label:
    runs-on: ubuntu-latest
    name: Approval Label
    steps:
      - name: Sudo GitHub Token
        id: sudo_github_token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.SUDO_GHA_CLIENT_ID }}
          private-key: ${{secrets.SUDO_GHA_APP_PRIVATE_KEY}}
          owner: ${{ github.repository_owner }}

      - name: Get pr info
        uses: octokit/graphql-action@ddde8ebb2493e79f390e6449c725c21663a67505 # v3.0.2
        id: get_pr_info
        with:
          variables: |
            owner: "Scalr"
            repo: ${{github.event.repository.name}}
            pr: ${{github.event.pull_request.number}}
          query: |
            query ($owner: String!, $repo: String!, $pr: Int!) {
              repository(owner: $owner, name: $repo) {
                pullRequest(number: $pr) {
                  reviewDecision
                  timelineItems(last: 250) {
                    edges {
                      node {
                        __typename
                      }
                    }
                  }
                }
              }
            }
        env:
          GITHUB_TOKEN: ${{steps.sudo_github_token.outputs.token}}

      - name: Set label
        if: github.event.review.state == 'approved' && fromJson(steps.get_pr_info.outputs.data).repository.pullRequest.reviewDecision == 'APPROVED'
        uses: actions-ecosystem/action-add-labels@bd52874380e3909a1ac983768df6976535ece7f8 # v1.1.0
        with:
          labels: approved
          github_token: ${{steps.sudo_github_token.outputs.token}}

      - name: Remove label
        if: github.event.review.state != 'approved' || fromJson(steps.get_pr_info.outputs.data).repository.pullRequest.reviewDecision != 'APPROVED'
        uses: actions-ecosystem/action-remove-labels@2ce5d41b4b6aa8503e285553f75ed56e0a40bae0 # v1.3.0
        with:
          labels: approved
          github_token: ${{steps.sudo_github_token.outputs.token}}
