name: Create Jira Tickets from Security Alerts
permissions:
  contents: read
  security-events: write
on:
  schedule:
    - cron: '0 */6 * * *'  #Runs every 6 hours
  workflow_dispatch:
jobs:
  create_ticket:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Scalr'
    steps:
      - name: Generate GitHub Token
        id: generate_token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.SUDO_GHA_CLIENT_ID }}
          private-key: ${{secrets.SUDO_GHA_APP_PRIVATE_KEY}}
          owner: ${{ github.repository_owner }}

      - name: Checkout Actions
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          token: ${{ steps.generate_token.outputs.token }}
          repository: Scalr/actions
          path: actions
          ref: master

      - name: Run Security Alerts Checker
        uses: ./actions/security-jira-ticket
        with:
          github_repository: ${{ github.repository }}
          github_token: ${{ steps.generate_token.outputs.token }}
          jira_token: ${{ secrets.JIRA_TOKEN }}
          jira_user: ${{ vars.JIRA_USER }}
          jira_host: ${{ vars.JIRA_HOST }}
          jira_project: ${{ vars.JIRA_PROJECT }}
